from enum import Enum, auto

class ObservationType(str, Enum):
    PACKET = "PACKET"
    FLOW = "FLOW"
    DNS = "DNS"
    TLS = "TLS"
    QUIC = "QUIC"

class ControlType(str, Enum):
    SOURCE_STARTED = "SOURCE_STARTED"
    SOURCE_PAUSED = "SOURCE_PAUSED"
    SOURCE_ENDED = "SOURCE_ENDED"
    SOURCE_FAILED = "SOURCE_FAILED"
    WATERMARK_ADVANCED = "WATERMARK_ADVANCED"
    QUALITY_GAP_OPENED = "QUALITY_GAP_OPENED"
    QUALITY_GAP_CLOSED = "QUALITY_GAP_CLOSED"
    PARSER_ERROR_OBSERVED = "PARSER_ERROR_OBSERVED"
    LANE_HEALTH_CHANGED = "LANE_HEALTH_CHANGED"
    SCIENTIFIC_STATUS_IMPORTED = "SCIENTIFIC_STATUS_IMPORTED"
    INTEGRATION_STATUS_CHANGED = "INTEGRATION_STATUS_CHANGED"
    OPERATIONAL_HEALTH_CHANGED = "OPERATIONAL_HEALTH_CHANGED"
    ADMISSION_REJECTED = "ADMISSION_REJECTED"
    ERROR = "ERROR"
    GAP_ACTION_STATUS = "GAP_ACTION_STATUS"
    LATE_EVENT_OBSERVED = "LATE_EVENT_OBSERVED"

class OfficialPsCategory(str, Enum):
    DDOS = "DDOS"
    C2_BEACONING = "C2_BEACONING"
    DGA_AND_DNS_TUNNELLING = "DGA_AND_DNS_TUNNELLING"
    ENCRYPTED_SESSIONS = "ENCRYPTED_SESSIONS"
    RECONNAISSANCE_AND_PORT_SCANNING = "RECONNAISSANCE_AND_PORT_SCANNING"
    DATA_EXFILTRATION = "DATA_EXFILTRATION"

class AnalyticFamily(str, Enum):
    DDOS = "DDOS"
    C2 = "C2"
    DGA = "DGA"
    DNS_TUNNELLING = "DNS_TUNNELLING"
    ENCRYPTED_SESSION = "ENCRYPTED_SESSION"
    RECON = "RECON"
    UNUSUAL_TRANSFER = "UNUSUAL_TRANSFER"

class IntegrationStatus(str, Enum):
    RESEARCHING = "RESEARCHING"
    OBSERVATION_CONTRACT_READY = "OBSERVATION_CONTRACT_READY"
    RUNTIME_SCAFFOLD_READY = "RUNTIME_SCAFFOLD_READY"
    BASELINE_IMPLEMENTED = "BASELINE_IMPLEMENTED"
    DEMO_READY = "DEMO_READY"

class OperationalHealth(str, Enum):
    HEALTHY = "HEALTHY"
    BACKPRESSURED = "BACKPRESSURED"
    STALLED = "STALLED"
    FAILED = "FAILED"
    DISABLED = "DISABLED"
    SHUTTING_DOWN = "SHUTTING_DOWN"

class ScientificStatus(str, Enum):
    ANALYTIC_UNAVAILABLE = "ANALYTIC_UNAVAILABLE"
    EVIDENCE_CONSTRUCTION = "EVIDENCE_CONSTRUCTION"
    BASELINE_UNDER_VALIDATION = "BASELINE_UNDER_VALIDATION"
    ANALYTIC_VALIDATING = "ANALYTIC_VALIDATING"
    MODEL_VALIDATED = "MODEL_VALIDATED"

class AdmissionReason(str, Enum):
    """Rejection reasons only. The positive case is AdmissionDecision.admitted == True."""
    PREREQUISITE_MISSING = "PREREQUISITE_MISSING"
    UNSUPPORTED_OBSERVATION_CONTRACT = "UNSUPPORTED_OBSERVATION_CONTRACT"
    INSUFFICIENT_VISIBILITY = "INSUFFICIENT_VISIBILITY"
    ANALYTIC_UNAVAILABLE = "ANALYTIC_UNAVAILABLE"
    UNSUPPORTED_FINALITY = "UNSUPPORTED_FINALITY"
    UNSUPPORTED_AVAILABILITY = "UNSUPPORTED_AVAILABILITY"
    # NOTE: INSUFFICIENT_HISTORY and STATE_EVICTED must NEVER appear in
    # IngestAdmissionDecision — they are EvaluationReadiness states (IC-16).
    # They are listed here because they CAN appear in historical/audit records
    # but IngestAdmissionDecision.evaluate() must not set them.
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    STATE_EVICTED = "STATE_EVICTED"

class GapAction(str, Enum):
    CONTINUE_WITH_QUALITY_FLAG = "CONTINUE_WITH_QUALITY_FLAG"
    RESET_AFFECTED_STATE = "RESET_AFFECTED_STATE"
    REENTER_WARMUP = "REENTER_WARMUP"
    ABSTAIN_UNTIL_RECOVERED = "ABSTAIN_UNTIL_RECOVERED"
    DISABLE_LANE = "DISABLE_LANE"

class ResultType(str, Enum):
    THREAT_ALERT = "THREAT_ALERT"
    REVIEW_FINDING = "REVIEW_FINDING"
    ANALYTIC_UNAVAILABLE = "ANALYTIC_UNAVAILABLE"
    PREREQUISITE_MISSING = "PREREQUISITE_MISSING"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    QUALITY_DEGRADED = "QUALITY_DEGRADED"
    PLUGIN_STATUS = "PLUGIN_STATUS"
    CORRELATION_FINDING = "CORRELATION_FINDING"

class AnalyticUnavailableReason(str, Enum):
    # Reason codes for AnalyticUnavailable
    SCIENTIFIC_NOT_READY = "SCIENTIFIC_NOT_READY"
    SEMANTIC_TARGET_UNDEFINED = "SEMANTIC_TARGET_UNDEFINED"
    DATA_NOT_ADMITTED = "DATA_NOT_ADMITTED"
    UNSUPPORTED_OBSERVATION_CONTRACT = "UNSUPPORTED_OBSERVATION_CONTRACT"
    IMPLEMENTATION_NOT_READY = "IMPLEMENTATION_NOT_READY"
    GOVERNANCE_DISABLED = "GOVERNANCE_DISABLED"

class SourceKind(str, Enum):
    PCAP = "PCAP"
    LIVE = "LIVE"
    FLOW_EXPORT = "FLOW_EXPORT"
    ZEEK = "ZEEK"
    SURICATA = "SURICATA"
    DERIVED = "DERIVED"

class TimestampSemantics(str, Enum):
    SOURCE_EVENT_TIME = "SOURCE_EVENT_TIME"
    FLOW_START = "FLOW_START"
    FLOW_END = "FLOW_END"
    EXPORT_TIME = "EXPORT_TIME"
    OTHER = "OTHER"

class WireDirection(str, Enum):
    FORWARD = "FORWARD"
    REVERSE = "REVERSE"
    UNKNOWN = "UNKNOWN"

class DirectionBasis(str, Enum):
    SOURCE_RECORD_ORDER = "SOURCE_RECORD_ORDER"
    CAPTURE_INTERFACE = "CAPTURE_INTERFACE"
    FLOW_EXPORTER = "FLOW_EXPORTER"
    CLIENT_SERVER_ROLE = "CLIENT_SERVER_ROLE"
    LOCAL_EXTERNAL_POLICY = "LOCAL_EXTERNAL_POLICY"
    UNKNOWN = "UNKNOWN"

class IdentityBasis(str, Enum):
    OBSERVED_IDENTIFIER = "OBSERVED_IDENTIFIER"
    SOURCE_DECLARED_ROLE = "SOURCE_DECLARED_ROLE"
    POLICY_DECLARED_ROLE = "POLICY_DECLARED_ROLE"
    UNKNOWN = "UNKNOWN"

class VisibilityCapability(str, Enum):
    FORWARD_FACTS = "FORWARD_FACTS"
    REVERSE_FACTS = "REVERSE_FACTS"
    PACKET_FACTS = "PACKET_FACTS"
    FLOW_FACTS = "FLOW_FACTS"
    CLEAR_DNS_FIELDS = "CLEAR_DNS_FIELDS"
    TLS_HANDSHAKE_METADATA = "TLS_HANDSHAKE_METADATA"
    TLS_RECORD_METADATA = "TLS_RECORD_METADATA"
    QUIC_OUTER_METADATA = "QUIC_OUTER_METADATA"

class CapabilityState(str, Enum):
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    DEGRADED = "DEGRADED"
    UNKNOWN = "UNKNOWN"

class QualityFact(str, Enum):
    PACKET_LOSS = "PACKET_LOSS"
    SAMPLING = "SAMPLING"
    PARSER = "PARSER"
    CAPTURE_GAP = "CAPTURE_GAP"

class QualityState(str, Enum):
    CLEAR = "CLEAR"
    DEGRADED = "DEGRADED"
    UNKNOWN = "UNKNOWN"

class Finality(str, Enum):
    CURRENT = "CURRENT"
    INTERMEDIATE = "INTERMEDIATE"
    TERMINAL = "TERMINAL"
    UNKNOWN = "UNKNOWN"

class AvailabilityBasis(str, Enum):
    IMMEDIATE = "IMMEDIATE"
    WINDOW_DERIVED = "WINDOW_DERIVED"
    REVERSE_DEPENDENT = "REVERSE_DEPENDENT"
    FLOW_END_ONLY = "FLOW_END_ONLY"
    OTHER = "OTHER"

class QualityGapReason(str, Enum):
    UPSTREAM_LOSS = "UPSTREAM_LOSS"
    ROUTER_LOSS = "ROUTER_LOSS"
    QUEUE_SATURATION = "QUEUE_SATURATION"
    PARSER_FAILURE = "PARSER_FAILURE"
    CAPTURE_GAP = "CAPTURE_GAP"
    UNKNOWN = "UNKNOWN"

class EvidenceReadiness(str, Enum):
    READY = "READY"
    WARMING_UP = "WARMING_UP"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    STATE_EVICTED = "STATE_EVICTED"
    ABSTAINING = "ABSTAINING"
    TERMINAL_EVIDENCE_PENDING = "TERMINAL_EVIDENCE_PENDING"

class QualityCondition(str, Enum):
    SUFFICIENT = "SUFFICIENT"
    DEGRADED = "DEGRADED"
    GAP_ACTIVE = "GAP_ACTIVE"
    UNKNOWN = "UNKNOWN"
